// Extended PDF exports matching the 'EIS for English' reference format:
//   1. Teacher Plan  (timing script, grammar notes, materials, activities with scripts/how-to-run/tips)
//   2. Student Activity Sheets  (name/date header + numbered exercises + challenges)
//   3. Answer Key
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const LIME = [166, 226, 46];
const BLACK = [10, 10, 10];

function docHeader(doc, teacher, subtitle) {
  doc.setFillColor(...BLACK);
  doc.rect(0, 0, 210, 22, "F");
  doc.setFillColor(...LIME);
  doc.rect(0, 22, 210, 1.2, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("[THE] TEACHKIT", 14, 13);
  if (subtitle) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(220, 220, 220);
    doc.text(subtitle, 14, 19);
  }
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(200, 200, 200);
  const line = [teacher?.full_name, teacher?.school_name, teacher?.school_city].filter(Boolean).join(" • ");
  if (line) doc.text(line, 196, 13, { align: "right" });
}

function docFooter(doc, i, total) {
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(`Page ${i} / ${total}`, 196, 290, { align: "right" });
  doc.text("Generated by THE TEACHKIT", 14, 290);
}

function paginate(doc, teacher, subtitle) {
  const pages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    if (i > 1) docHeader(doc, teacher, subtitle);
    docFooter(doc, i, pages);
  }
}

function sectionTitle(doc, y, text) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...BLACK);
  doc.text(text.toUpperCase(), 14, y);
  doc.setDrawColor(...LIME);
  doc.setLineWidth(0.8);
  doc.line(14, y + 1.5, 14 + doc.getTextWidth(text.toUpperCase()) + 6, y + 1.5);
  return y + 6;
}

export function exportTeacherPlanPdf(lesson, teacher) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const subtitle = `Teacher Plan · Week ${lesson.week} · CEFR ${lesson.cefr_level}`;
  docHeader(doc, teacher, subtitle);
  const pack = lesson.pack || {};

  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(lesson.title, 14, 38, { maxWidth: 180 });

  // Meta table
  autoTable(doc, {
    startY: 46,
    theme: "grid",
    head: [["Field", "Details"]],
    body: [
      ["Learner", `Age 10-12 · ${teacher?.class_level || "CM2/6ème"} · French L1`],
      ["Lesson aim", pack.lesson_aim || (lesson.objectives || []).join(" ")],
      ["Grammar focus", lesson.grammar],
      ["Key vocabulary", (lesson.vocabulary || []).join(", ")],
      ["Materials", (lesson.materials || []).map((m) => `• ${m}`).join("\n")],
    ],
    headStyles: { fillColor: BLACK, textColor: 255 },
    styles: { fontSize: 9, cellPadding: 3, valign: "top" },
    columnStyles: { 0: { cellWidth: 38, fontStyle: "bold" }, 1: { cellWidth: 152 } },
  });

  let y = doc.lastAutoTable.finalY + 6;

  // Grammar notes
  if (pack.grammar_notes?.length) {
    y = sectionTitle(doc, y, "Grammar notes");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    pack.grammar_notes.forEach((n) => {
      const lines = doc.splitTextToSize(`• ${n}`, 180);
      doc.text(lines, 14, y);
      y += lines.length * 4.5;
    });
    y += 2;
  }

  // Timing summary table
  const timing = pack.timing || lessonToLegacyTiming(lesson);
  if (y > 240) { doc.addPage(); y = 40; }
  y = sectionTitle(doc, y, "Suggested timing (55–60 min)");
  autoTable(doc, {
    startY: y,
    head: [["#", "Activity", "Minutes"]],
    body: timing.map((t) => [t.n, t.title, `${t.minutes} min`]),
    headStyles: { fillColor: LIME, textColor: BLACK, fontStyle: "bold" },
    styles: { fontSize: 9, cellPadding: 2.5 },
    columnStyles: { 0: { cellWidth: 12 }, 1: { cellWidth: 140 }, 2: { cellWidth: 30 } },
  });
  y = doc.lastAutoTable.finalY + 6;

  // Per-activity scripts
  timing.forEach((t) => {
    if (y > 250) { doc.addPage(); y = 40; }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(...BLACK);
    doc.text(`${t.n}. ${t.title} · ${t.minutes} min`, 14, y);
    doc.setDrawColor(...LIME);
    doc.line(14, y + 1.5, 60, y + 1.5);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    if (t.teacher_script) {
      doc.setFont("helvetica", "bold");
      doc.text("Teacher script:", 14, y); y += 4.5;
      doc.setFont("helvetica", "italic");
      const l1 = doc.splitTextToSize(`"${t.teacher_script}"`, 180);
      doc.text(l1, 14, y); y += l1.length * 4.5 + 1;
    }
    if (t.how_to_run) {
      doc.setFont("helvetica", "bold");
      doc.setFont("helvetica", "bold");
      doc.text("How to run it:", 14, y); y += 4.5;
      doc.setFont("helvetica", "normal");
      const l2 = doc.splitTextToSize(t.how_to_run, 180);
      doc.text(l2, 14, y); y += l2.length * 4.5 + 1;
    }
    if (t.teacher_tip) {
      doc.setFont("helvetica", "bold");
      doc.setTextColor(0, 100, 0);
      doc.text("Teacher tip:", 14, y); y += 4.5;
      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BLACK);
      const l3 = doc.splitTextToSize(t.teacher_tip, 180);
      doc.text(l3, 14, y); y += l3.length * 4.5 + 2;
    }
    y += 3;
  });

  paginate(doc, teacher, subtitle);
  doc.save(`teachkit-week-${lesson.week}-teacher-plan.pdf`);
}

export function exportStudentSheetsPdf(lesson, teacher) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const subtitle = `Student Activity Sheets · Week ${lesson.week}`;
  docHeader(doc, teacher, subtitle);
  const pack = lesson.pack;
  if (!pack?.student_pages) { doc.text("No student pages generated yet.", 14, 40); doc.save("empty.pdf"); return; }

  // Cover
  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(lesson.title, 14, 40, { maxWidth: 180 });
  doc.setFontSize(11);
  doc.text(`Week ${lesson.week} · CEFR ${lesson.cefr_level}`, 14, 50);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Name: ______________________________     Date: ______________", 14, 62);

  pack.student_pages.forEach((p, idx) => {
    doc.addPage();
    docHeader(doc, teacher, subtitle);
    let y = 40;
    doc.setTextColor(...BLACK);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(16);
    doc.text(`Page ${p.page || idx + 1} · ${p.title}`, 14, y);
    doc.setDrawColor(...LIME);
    doc.line(14, y + 2, 60, y + 2);
    y += 8;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text("Name: ______________________________     Date: ______________", 14, y); y += 8;
    if (p.instructions) {
      doc.setFont("helvetica", "italic");
      const li = doc.splitTextToSize(p.instructions, 180);
      doc.text(li, 14, y);
      y += li.length * 4.5 + 3;
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    (p.items || []).forEach((it, i) => {
      if (y > 265) { doc.addPage(); docHeader(doc, teacher, subtitle); y = 40; }
      if (typeof it === "string") {
        const lines = doc.splitTextToSize(`${i + 1}. ${it}`, 180);
        doc.text(lines, 14, y);
        y += lines.length * 5;
        // Answer line
        doc.setDrawColor(180, 180, 180);
        doc.line(14, y, 194, y);
        y += 6;
      } else if (typeof it === "object") {
        const q = doc.splitTextToSize(`${i + 1}. ${it.q}`, 180);
        doc.text(q, 14, y); y += q.length * 5;
        ["a", "b", "c"].forEach((opt) => {
          if (it[opt]) { doc.text(`   ${opt}) ${it[opt]}`, 16, y); y += 5; }
        });
        y += 3;
      }
    });
    if (p.challenge) {
      if (y > 260) { doc.addPage(); docHeader(doc, teacher, subtitle); y = 40; }
      y += 4;
      doc.setFont("helvetica", "bold");
      doc.setTextColor(...BLACK);
      doc.text("★ Challenge — for early finishers ★", 14, y); y += 6;
      doc.setFont("helvetica", "normal");
      const c = doc.splitTextToSize(p.challenge, 180);
      doc.text(c, 14, y);
    }
  });

  paginate(doc, teacher, subtitle);
  doc.save(`teachkit-week-${lesson.week}-student-sheets.pdf`);
}

export function exportAnswerKeyPdf(lesson, teacher) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const subtitle = `Answer Key · Week ${lesson.week}`;
  docHeader(doc, teacher, subtitle);
  const pack = lesson.pack;
  if (!pack?.answer_key) { doc.text("No answer key generated yet.", 14, 40); doc.save("empty.pdf"); return; }

  doc.setTextColor(...BLACK);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(`${lesson.title} — Answer Key`, 14, 40, { maxWidth: 180 });

  let y = 52;
  const sections = [
    ["Page 1 · Gap Fill", pack.answer_key.page_1_gap_fill],
    ["Page 2 · True or False", pack.answer_key.page_2_true_false],
    ["Page 3 · Multiple Choice", pack.answer_key.page_3_multiple_choice],
    ["Page 4 · Controlled Speaking — sample answers", pack.answer_key.page_4_sample_answers],
  ];

  sections.forEach(([title, arr]) => {
    if (!arr) return;
    if (y > 250) { doc.addPage(); docHeader(doc, teacher, subtitle); y = 40; }
    y = sectionTitle(doc, y, title);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    arr.forEach((v, i) => {
      const lines = doc.splitTextToSize(`${i + 1}. ${v}`, 180);
      doc.text(lines, 14, y);
      y += lines.length * 5;
    });
    y += 4;
  });

  paginate(doc, teacher, subtitle);
  doc.save(`teachkit-week-${lesson.week}-answer-key.pdf`);
}

// Legacy fallback if lesson pack has no timing (before AI enrichment)
function lessonToLegacyTiming(lesson) {
  const out = [];
  let n = 1;
  ["presentation", "practice", "production"].forEach((p) => {
    const phase = lesson.ppp?.[p];
    if (!phase) return;
    (phase.activities || []).forEach((a) => {
      out.push({
        n: n++,
        title: `${phase.phase}: ${a.title}`,
        minutes: Math.round((phase.duration_min || 15) / (phase.activities.length || 1)),
        teacher_script: "",
        how_to_run: a.description,
        teacher_tip: "",
      });
    });
  });
  return out;
}
